export const IDENTITY_SCENARIOS = [
  "IDENTITY_SUCCESS",
  "IDENTITY_INCONCLUSIVE",
  "IDENTITY_TIMEOUT",
  "IDENTITY_PROVIDER_ERROR",
  "DOCUMENT_INVALID_REVIEW",
  "LIVENESS_INCONCLUSIVE",
  "LIVENESS_FAILED_REVIEW",
  "FACE_NO_MATCH_REVIEW",
] as const;

export type IdentityScenario = typeof IDENTITY_SCENARIOS[number];

export const BACKGROUND_SCENARIOS = [
  "BACKGROUND_SUCCESS",
  "BACKGROUND_INCONCLUSIVE",
  "BACKGROUND_TIMEOUT",
  "BACKGROUND_PROVIDER_ERROR",
  "BACKGROUND_ADVERSE_REVIEW",
  "BACKGROUND_MANUAL_CONFIRMATION",
] as const;

export type BackgroundScenario = typeof BACKGROUND_SCENARIOS[number];

export const MESSAGING_SCENARIOS = [
  "MESSAGE_SUCCESS",
  "MESSAGE_TIMEOUT",
  "MESSAGE_PROVIDER_ERROR",
  "MESSAGE_DUPLICATE",
] as const;

export type MessagingScenario = typeof MESSAGING_SCENARIOS[number];
