drop trigger if exists verified_access_policies_validate_state_machine on public.verified_access_policies;
drop trigger if exists verified_access_network_appeals_validate_state_machine on public.verified_access_network_appeals;
drop trigger if exists verified_access_network_signals_validate_state_machine on public.verified_access_network_signals;
drop trigger if exists verified_access_network_cases_validate_state_machine on public.verified_access_network_security_cases;
drop trigger if exists verified_access_network_links_validate_state_machine on public.verified_access_network_subject_links;
drop trigger if exists verified_access_network_identifiers_validate_state_machine on public.verified_access_network_subject_identifiers;
drop trigger if exists verified_access_network_subjects_validate_state_machine on public.verified_access_network_subjects;
drop trigger if exists verified_access_participants_validate_state_machines on public.verified_access_participants;
drop trigger if exists verified_access_slots_validate_state_machine on public.verified_access_participant_slots;
drop trigger if exists verified_access_requests_validate_state_machine on public.verified_access_requests;

drop function if exists public.verified_access_retire_policy(uuid, uuid, text, text, text);
drop function if exists public.verified_access_activate_policy(uuid, uuid, text, text, text);
drop function if exists public.verified_access_create_policy_draft(uuid, jsonb, text, uuid, text);
drop function if exists public.verified_access_enqueue_outbox_event(uuid, text, uuid, text, text, jsonb);
drop function if exists public.verified_access_write_audit_event(uuid, text, text, text, uuid, text, text, text, jsonb);
drop function if exists public.verified_access_assert_sanitized_payload(jsonb, text);
drop function if exists public.verified_access_validate_policy_state_machine();
drop function if exists public.verified_access_policy_content_checksum(jsonb);
drop function if exists public.verified_access_validate_policy_payload(jsonb);
drop function if exists public.verified_access_policy_payload_allowed_keys();
drop function if exists public.verified_access_validate_network_appeal_state_machine();
drop function if exists public.verified_access_validate_network_signal_state_machine();
drop function if exists public.verified_access_validate_network_case_state_machine();
drop function if exists public.verified_access_validate_network_link_state_machine();
drop function if exists public.verified_access_validate_network_identifier_state_machine();
drop function if exists public.verified_access_validate_network_subject_state_machine();
drop function if exists public.verified_access_validate_participant_state_machines();
drop function if exists public.verified_access_validate_slot_state_machine();
drop function if exists public.verified_access_validate_request_state_machine();
drop function if exists public.verified_access_transition_allowed(text, text, text);
